name: Hello World

on: 
  - push
  - pull_request

jobs:
  with-conan:
    runs-on: ubuntu-22.04
    steps:
    - name: install conan
      run: |
        pip install conan==2.0.9
        conan profile detect
    - name: install cmake
      uses: lukka/get-cmake@v3.27.4

    - uses: actions/checkout@v3
    - name: install sdplog
      run: conan install .
    - name: build app
      run: |
        cmake --preset conan-release
        cmake --build --preset conan-release
    - name: run app
      run: ./build/Release/app
